version: '3.1'

services:

  postgres_db:
    image: postgres:15.3-alpine
    env_file:
      - .env.docker
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    depends_on:
      postgres_db:
        condition: service_healthy
    command: >
      sh -c "python main.py"
    env_file:
      - .env.docker
    volumes:
      - .:/app

volumes:
  pg_data: